apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: dotnet-api-template
  title: .NET 9 API Template
  description: Scaffolds a .NET 9 Web API project
  tags:
    - dotnet
    - api
    - microservice
spec:
  owner: platform