apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MyOrg.${{ values.projectName }}
  description: MyOrg.${{ values.projectName }} project.
  tags:
    - dotnet
    - api
    - microservice
    - ${{ values.owner }}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
